spring:
  scheduler:
    rate: 60000
  cloud:
    config:
      enabled: false
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: <email>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  host: https://cdn-api.co-vin.in/api
  findByPinEndpoint: /v2/appointment/sessions/public/findByPin
  calendarByPinEndpoint: /v2/appointment/sessions/public/calendarByPin

search-details:
  -
    pincode: <pincode1>
    recipients:
      - <email1>
      - <email2>
      - <email3>

  -
    pincode: <pincode2>
    recipients:
      - <email1>

logging.level.com.cowin.vaccinefinder.client.CowinFeignClient: DEBUG